buildscript {
    repositories {
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
}

apply plugin: 'java'
apply plugin: 'signing'
apply plugin: 'maven-publish'

group = 'com.dotcms'
version = '1.5'

repositories {
    mavenCentral()
}

compileJava {
    sourceCompatibility = 11
    targetCompatibility = 11
}

dependencies {
    implementation group: 'org.apache.tomcat', name: 'tomcat-catalina', version: '9.0.108'
    implementation 'redis.clients:jedis:4.4.6'
    implementation group: 'org.apache.commons', name: 'commons-pool2', version: '2.11.1'
    testImplementation group: 'org.apache.tomcat', name: 'tomcat-coyote', version: '9.0.108'
}

tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    classifier = 'javadoc'
    from 'build/docs/javadoc'
}

tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allSource
    classifier = 'sources'
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

tasks.register('wrapper', Wrapper) {
    gradleVersion = '8.14'
}

tasks.withType(JavaCompile).configureEach {
    options.deprecation = true
}

// Maven publishing configuration for JFrog
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifact sourcesJar {
                classifier = 'sources'
            }

            artifact javadocJar {
                classifier = 'javadoc'
            }
        }
    }

    repositories {
        maven {
            url = uri('https://repo.dotcms.com/artifactory/libs-release-local')
            credentials {
                username = System.getenv("DOTCMS_ARTIFACTORY_USERNAME")
                password = System.getenv("DOTCMS_ARTIFACTORY_PASSWORD")
            }
        }
    }
}

// Custom alias task for JFrog publishing
tasks.register("jfrogPublish") {
    group = "publishing"
    description = "Publishes artifacts to JFrog Artifactory"

    // only publish the mavenJava publication to the defined repo
    dependsOn "publishMavenJavaPublicationToMavenRepository"
}
