buildscript {
    repositories {
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'signing'
apply plugin: 'maven-publish'

group = 'com.dotcms'
version = '1.4'

repositories {
    mavenCentral()
}

compileJava {
    sourceCompatibility = 11
    targetCompatibility = 11
}

dependencies {
    compile group: 'org.apache.tomcat', name: 'tomcat-catalina', version: '9.0.108'
    implementation 'redis.clients:jedis:4.4.6'
    compile group: 'org.apache.commons', name: 'commons-pool2', version: '2.11.1'
    testCompile group: 'org.apache.tomcat', name: 'tomcat-coyote', version: '9.0.108'
}

tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    classifier = 'javadoc'
    from 'build/docs/javadoc'
}

tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allSource
    classifier = 'sources'
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

tasks.register('wrapper', Wrapper) {
    gradleVersion = '4.10.2'
}

tasks.withType(JavaCompile).configureEach {
    options.deprecation = true
}

// Maven configuration for JFrog
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifact sourcesJar {
                classifier = 'sources'
            }

            artifact javadocJar {
                classifier = 'javadoc'
            }
        }
    }

    repositories {
        maven {
            url 'https://repo.dotcms.com/artifactory'
            credentials {
                username = System.getenv("DOTCMS_ARTIFACTORY_USERNAME")
                password = System.getenv("DOTCMS_ARTIFACTORY_PASSWORD")
            }
        }
    }
}
